# Generated by Django 2.2.7 on 2019-12-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20191202_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
