# Generated by Django 2.2.7 on 2019-12-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
